In [1]:
# Cleaning up data

In [2]:
import numpy as np
import pandas as pd

In [3]:
incidents = pd.read_csv('incd.csv')
income = pd.read_csv('income.csv')
deaths = pd.read_csv('death.csv')

In [4]:
incidents

,index,County,FIPS,"Age-Adjusted Incidence Rate(Ê) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,Average Annual Count,Recent Trend,Recent 5-Year Trend (ˆ) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,0,US (SEER+NPCR),0,62.4,62.3,62.6,214614,falling,-2.5,-3,-2
1,1,"Autauga County, Alabama",1001,74.9,65.1,85.7,43,stable,0.5,-14.9,18.6
2,2,"Baldwin County, Alabama",1003,66.9,62.4,71.7,170,stable,3,-10.2,18.3
3,3,"Barbour County, Alabama",1005,74.6,61.8,89.4,25,stable,-6.4,-18.3,7.3
4,4,"Bibb County, Alabama",1007,86.4,71,104.2,23,stable,-4.5,-31.4,32.9
...,...,...,...,...,...,...,...,...,...,...,...
3136,3136,"Sweetwater County, Wyoming",56037,39.9,30.5,51.1,14,stable,12.6,-18.1,54.9
3137,3137,"Teton County, Wyoming",56039,23.7,14.7,36.1,5,stable,-19.6,-35.5,0.1
3138,3138,"Uinta County, Wyoming",56041,31.7,20.8,46.1,6,stable,-0.1,-18.3,22
3139,3139,"Washakie County, Wyoming",56043,50,33.8,72.2,6,stable,13.5,-12.2,46.7
3140,3140,"Weston County, Wyoming",56045,44.9,27.9,69.6,4,stable,-26.2,-65.4,57.4

In [5]:
incidents.drop(index=0,axis=0) # Remove Total Row
# Remove unwanted values
a = incidents[incidents['Age-Adjusted Incidence Rate(Ê) - cases per 100,000'] == '*'].index
b = incidents[incidents['Age-Adjusted Incidence Rate(Ê) - cases per 100,000'] == '* '].index
c = incidents[incidents['Age-Adjusted Incidence Rate(Ê) - cases per 100,000'] == ' '].index

incidents.drop(a,inplace=True)
incidents.drop(b,inplace=True)
incidents.drop(c,inplace=True)

incidents = incidents[incidents['Average Annual Count'].str.contains('3 or fewer')==False]
incidents = incidents[incidents['Age-Adjusted Incidence Rate(Ê) - cases per 100,000'].str.contains('#')==False]
incidents = incidents[incidents['Age-Adjusted Incidence Rate(Ê) - cases per 100,000'].str.contains('_')==False]

In [6]:
# Horrifying. Whoever thought this dataset was okay to submit is fucking insane because what the fuck is this

In [7]:
incidents

,index,County,FIPS,"Age-Adjusted Incidence Rate(Ê) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,Average Annual Count,Recent Trend,Recent 5-Year Trend (ˆ) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,0,US (SEER+NPCR),0,62.4,62.3,62.6,214614,falling,-2.5,-3,-2
1,1,"Autauga County, Alabama",1001,74.9,65.1,85.7,43,stable,0.5,-14.9,18.6
2,2,"Baldwin County, Alabama",1003,66.9,62.4,71.7,170,stable,3,-10.2,18.3
3,3,"Barbour County, Alabama",1005,74.6,61.8,89.4,25,stable,-6.4,-18.3,7.3
4,4,"Bibb County, Alabama",1007,86.4,71,104.2,23,stable,-4.5,-31.4,32.9
...,...,...,...,...,...,...,...,...,...,...,...
3136,3136,"Sweetwater County, Wyoming",56037,39.9,30.5,51.1,14,stable,12.6,-18.1,54.9
3137,3137,"Teton County, Wyoming",56039,23.7,14.7,36.1,5,stable,-19.6,-35.5,0.1
3138,3138,"Uinta County, Wyoming",56041,31.7,20.8,46.1,6,stable,-0.1,-18.3,22
3139,3139,"Washakie County, Wyoming",56043,50,33.8,72.2,6,stable,13.5,-12.2,46.7
3140,3140,"Weston County, Wyoming",56045,44.9,27.9,69.6,4,stable,-26.2,-65.4,57.4

In [8]:
#clean = incidents['County'].str[:-6] # Remove excess (6,10) on County

In [9]:
clean = incidents['County'].str.split(',',n=1,expand=True) # Split column to County Name and State Name

In [10]:
clean = clean.rename(columns={0:'County_Name',1:'State_Name'}) # Rename Columns

In [11]:
incidents = incidents.rename(columns={'Age-Adjusted Incidence Rate(Ê) - cases per 100,000':'Age-Adjusted Incidence Rate'})

In [12]:
incidents = pd.concat([incidents,clean],axis=1) # Add clean columns in!

In [13]:
#incidents = incidents[incidents['State_Name'].str.contains('Wash')==True]

In [14]:
incidents.reset_index()

,level_0,index,County,FIPS,Age-Adjusted Incidence Rate,Lower 95% Confidence Interval,Upper 95% Confidence Interval,Average Annual Count,Recent Trend,Recent 5-Year Trend (ˆ) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1,County_Name,State_Name
0,0,0,US (SEER+NPCR),0,62.4,62.3,62.6,214614,falling,-2.5,-3,-2,US (SEER+NPCR),None
1,1,1,"Autauga County, Alabama",1001,74.9,65.1,85.7,43,stable,0.5,-14.9,18.6,Autauga County,Alabama
2,2,2,"Baldwin County, Alabama",1003,66.9,62.4,71.7,170,stable,3,-10.2,18.3,Baldwin County,Alabama
3,3,3,"Barbour County, Alabama",1005,74.6,61.8,89.4,25,stable,-6.4,-18.3,7.3,Barbour County,Alabama
4,4,4,"Bibb County, Alabama",1007,86.4,71,104.2,23,stable,-4.5,-31.4,32.9,Bibb County,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2635,3136,3136,"Sweetwater County, Wyoming",56037,39.9,30.5,51.1,14,stable,12.6,-18.1,54.9,Sweetwater County,Wyoming
2636,3137,3137,"Teton County, Wyoming",56039,23.7,14.7,36.1,5,stable,-19.6,-35.5,0.1,Teton County,Wyoming
2637,3138,3138,"Uinta County, Wyoming",56041,31.7,20.8,46.1,6,stable,-0.1,-18.3,22,Uinta County,Wyoming
2638,3139,3139,"Washakie County, Wyoming",56043,50,33.8,72.2,6,stable,13.5,-12.2,46.7,Washakie County,Wyoming
2639,3140,3140,"Weston County, Wyoming",56045,44.9,27.9,69.6,4,stable,-26.2,-65.4,57.4,Weston County,Wyoming

In [15]:
deaths

,index,County,FIPS,Met Objective of 45.5? (1),Age-Adjusted Death Rate,Lower 95% Confidence Interval for Death Rate,Upper 95% Confidence Interval for Death Rate,Average Deaths per Year,Recent Trend (2),Recent 5-Year Trend (2) in Death Rates,Lower 95% Confidence Interval for Trend,Upper 95% Confidence Interval for Trend
0,0,United States,0,No,46,45.9,46.1,"157,376",falling,-2.4,-2.6,-2.2
1,1,"Perry County, Kentucky",21193,No,125.6,108.9,144.2,43,stable,-0.6,-2.7,1.6
2,2,"Powell County, Kentucky",21197,No,125.3,100.2,155.1,18,stable,1.7,0,3.4
3,3,"North Slope Borough, Alaska",2185,No,124.9,73,194.7,5,**,**,**,**
4,4,"Owsley County, Kentucky",21189,No,118.5,83.1,165.5,8,stable,2.2,-0.4,4.8
...,...,...,...,...,...,...,...,...,...,...,...,...
3136,3136,"Yakutat City and Borough, Alaska<sup>3</sup>",2282,*,*,*,*,*,**,**,**,**
3137,3137,"Yukon-Koyukuk Census Area, Alaska",2290,*,*,*,*,*,**,**,**,**
3138,3138,"Zapata County, Texas",48505,*,*,*,*,*,*,*,*,*
3139,3139,"Zavala County, Texas",48507,*,*,*,*,*,**,**,**,**
3140,3140,"Ziebach County, South Dakota",46137,*,*,*,*,*,**,**,**,**

In [16]:
# Remove Total Row
deaths.drop(index=0,axis=0)
# Remove * values
x = deaths[deaths['Average Deaths per Year'] == '*'].index
deaths.drop(x,inplace=True)

#def removeQuote(object):
#    if deaths[deaths['Average Deaths per Year'].str.contains('"')] | deaths[deaths['Average Deaths per Year'].str.contains(',')]:
#        deaths[deaths['Average Deaths per Year'].str.replace('"','')]
#        deaths[deaths['Average Deaths per Year'].str.replace(',','')]
#deaths = deaths[deaths['Average Deaths per Year'].str.contains(',')==False]

In [17]:
clean = deaths['County'].str.split(',',n=1,expand=True) # Split Countys and State

In [18]:
clean = clean.rename(columns={0:'County_Name',1:'State_Name'}) # Rename columns to match

In [19]:
deaths = pd.concat([deaths,clean],axis=1) # Add clean columns in!

In [20]:
# Limit to WA
#deaths = deaths[deaths['State_Name'].str.contains('Washington')==True]

In [21]:
deaths.reset_index() # Cleaned data frame

,level_0,index,County,FIPS,Met Objective of 45.5? (1),Age-Adjusted Death Rate,Lower 95% Confidence Interval for Death Rate,Upper 95% Confidence Interval for Death Rate,Average Deaths per Year,Recent Trend (2),Recent 5-Year Trend (2) in Death Rates,Lower 95% Confidence Interval for Trend,Upper 95% Confidence Interval for Trend,County_Name,State_Name
0,0,0,United States,0,No,46,45.9,46.1,"157,376",falling,-2.4,-2.6,-2.2,United States,None
1,1,1,"Perry County, Kentucky",21193,No,125.6,108.9,144.2,43,stable,-0.6,-2.7,1.6,Perry County,Kentucky
2,2,2,"Powell County, Kentucky",21197,No,125.3,100.2,155.1,18,stable,1.7,0,3.4,Powell County,Kentucky
3,3,3,"North Slope Borough, Alaska",2185,No,124.9,73,194.7,5,**,**,**,**,North Slope Borough,Alaska
4,4,4,"Owsley County, Kentucky",21189,No,118.5,83.1,165.5,8,stable,2.2,-0.4,4.8,Owsley County,Kentucky
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2808,2808,2808,"Eagle County, Colorado",8037,Yes,14.9,8.7,23.6,5,falling,-4.9,-9.3,-0.3,Eagle County,Colorado
2809,2809,2809,"Summit County, Utah",49043,Yes,14.4,8.2,23.2,4,**,**,**,**,Summit County,Utah
2810,2810,2810,"Utah County, Utah",49049,Yes,12.4,10.7,14.4,37,falling,-2.8,-3.9,-1.8,Utah County,Utah
2811,2811,2811,"McKinley County, New Mexico",35031,Yes,11.6,8,16.2,7,falling,-3.2,-5.7,-0.7,McKinley County,New Mexico
2812,2812,2812,"Cache County, Utah",49005,Yes,9.2,6.4,12.8,7,stable,-0.7,-3,1.6,Cache County,Utah

In [22]:
income

,id,State_Code,State_Name,State_ab,County,City,Place,Type,Primary,Zip_Code,Area_Code,ALand,AWater,Lat,Lon,Mean,Median,Stdev,sum_w
0,1011000,1,Alabama,AL,Mobile County,Chickasaw,Chickasaw city,City,place,36611,251,10894952,909156.0,30.771450,-88.079697,38773,30506,33101.0,1638.260513
1,1011010,1,Alabama,AL,Barbour County,Louisville,Clio city,City,place,36048,334,26070325,23254.0,31.708516,-85.611039,37725,19528,43789.0,258.017685
2,1011020,1,Alabama,AL,Shelby County,Columbiana,Columbiana city,City,place,35051,205,44835274,261034.0,33.191452,-86.615618,54606,31930,57348.0,926.031000
3,1011030,1,Alabama,AL,Mobile County,Satsuma,Creola city,City,place,36572,251,36878729,2374530.0,30.874343,-88.009442,63919,52814,47707.0,378.114619
4,1011040,1,Alabama,AL,Mobile County,Dauphin Island,Dauphin Island,Town,place,36528,251,16204185,413605152.0,30.250913,-88.171268,77948,67225,54270.0,282.320328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32521,720296,72,Puerto Rico,PR,Adjuntas Municipio,Guaynabo,Adjuntas,Track,Track,970,787,589417,1691.0,18.397925,-66.130633,30649,13729,37977.0,1321.278082
32522,7202966,72,Puerto Rico,PR,Adjuntas Municipio,Aguada,Adjuntas,Track,Track,602,787,1801613,795887.0,18.385424,-67.203310,15520,9923,15541.0,238.813450
32523,7202976,72,Puerto Rico,PR,Adjuntas Municipio,Aguada,Adjuntas,Track,Track,602,787,11031227,0.0,18.356565,-67.180686,41933,34054,31539.0,313.551070
32524,7202986,72,Puerto Rico,PR,Adjuntas Municipio,Aguada,Adjuntas,Track,Track,602,787,0,33597561.0,18.412041,-67.213413,0,0,0.0,0.000000
32525,7202996,72,Puerto Rico,PR,Adjuntas Municipio,Aguadilla,Adjuntas,Track,Track,603,787,6476604,2717115.0,18.478094,-67.160453,28049,20229,33333.0,512.884803

In [23]:
income = income.rename(columns=({'County':'County_Name','Median':'Median_Income'})) # Rename income columns to match

In [24]:
# Initialize columns
cols_concat = ['County_Name', 'State_Name']

# Convert them to type str
income[cols_concat] = income[cols_concat].astype('str')

# Then concatenate them as follows
income['County'] = income[cols_concat].T.agg(', '.join)

In [25]:
income = income[income['Median_Income'] < 300000] # Remove counties with median salary above 300K

In [26]:
income = income[income['Median_Income'] > 0] #

In [27]:
#income = income[income['State_Name'].str.contains('Washington')==True]

In [28]:
income.reset_index()

,index,id,State_Code,State_Name,State_ab,County_Name,City,Place,Type,Primary,...,Area_Code,ALand,AWater,Lat,Lon,Mean,Median_Income,Stdev,sum_w,County
0,0,1011000,1,Alabama,AL,Mobile County,Chickasaw,Chickasaw city,City,place,...,251,10894952,909156.0,30.771450,-88.079697,38773,30506,33101.0,1638.260513,"Mobile County, Alabama"
1,1,1011010,1,Alabama,AL,Barbour County,Louisville,Clio city,City,place,...,334,26070325,23254.0,31.708516,-85.611039,37725,19528,43789.0,258.017685,"Barbour County, Alabama"
2,2,1011020,1,Alabama,AL,Shelby County,Columbiana,Columbiana city,City,place,...,205,44835274,261034.0,33.191452,-86.615618,54606,31930,57348.0,926.031000,"Shelby County, Alabama"
3,3,1011030,1,Alabama,AL,Mobile County,Satsuma,Creola city,City,place,...,251,36878729,2374530.0,30.874343,-88.009442,63919,52814,47707.0,378.114619,"Mobile County, Alabama"
4,4,1011040,1,Alabama,AL,Mobile County,Dauphin Island,Dauphin Island,Town,place,...,251,16204185,413605152.0,30.250913,-88.171268,77948,67225,54270.0,282.320328,"Mobile County, Alabama"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27919,32520,7202956,72,Puerto Rico,PR,Adjuntas Municipio,Adjuntas,Adjuntas,Track,Track,...,787,42529236,210360.0,18.155582,-66.701046,23682,15051,30309.0,615.289902,"Adjuntas Municipio, Puerto Rico"
27920,32521,720296,72,Puerto Rico,PR,Adjuntas Municipio,Guaynabo,Adjuntas,Track,Track,...,787,589417,1691.0,18.397925,-66.130633,30649,13729,37977.0,1321.278082,"Adjuntas Municipio, Puerto Rico"
27921,32522,7202966,72,Puerto Rico,PR,Adjuntas Municipio,Aguada,Adjuntas,Track,Track,...,787,1801613,795887.0,18.385424,-67.203310,15520,9923,15541.0,238.813450,"Adjuntas Municipio, Puerto Rico"
27922,32523,7202976,72,Puerto Rico,PR,Adjuntas Municipio,Aguada,Adjuntas,Track,Track,...,787,11031227,0.0,18.356565,-67.180686,41933,34054,31539.0,313.551070,"Adjuntas Municipio, Puerto Rico"
27923,32525,7202996,72,Puerto Rico,PR,Adjuntas Municipio,Aguadilla,Adjuntas,Track,Track,...,787,6476604,2717115.0,18.478094,-67.160453,28049,20229,33333.0,512.884803,"Adjuntas Municipio, Puerto Rico"

In [29]:
# Take slices from each dataframe with useful data

In [30]:
incident_slice = incidents[['Age-Adjusted Incidence Rate','County','Average Annual Count']]

In [31]:
income_slice = income[['City','County','State_Name','Median_Income']]

In [32]:
death_slice = deaths[['Age-Adjusted Death Rate','County','Average Deaths per Year']]

In [33]:
# Merge Income and Cancer Rates based on County Name

In [34]:
income_incident_data = pd.merge(income_slice,incident_slice,how='inner',on='County')

In [35]:
income_incident_data

,City,County,State_Name,Median_Income,Age-Adjusted Incidence Rate,Average Annual Count
0,Chickasaw,"Mobile County, Alabama",Alabama,30506,75.4,347
1,Satsuma,"Mobile County, Alabama",Alabama,52814,75.4,347
2,Dauphin Island,"Mobile County, Alabama",Alabama,67225,75.4,347
3,Mobile,"Mobile County, Alabama",Alabama,38231,75.4,347
4,Satsuma,"Mobile County, Alabama",Alabama,52275,75.4,347
...,...,...,...,...,...,...
24960,Cheyenne,"Albany County, Wyoming",Wyoming,69614,40.8,11
24961,Cheyenne,"Albany County, Wyoming",Wyoming,68371,40.8,11
24962,Diamondville,"Albany County, Wyoming",Wyoming,70752,40.8,11
24963,Casper,"Albany County, Wyoming",Wyoming,79809,40.8,11
24964,Powell,"Albany County, Wyoming",Wyoming,64557,40.8,11

In [36]:
income_death_data = pd.merge(income_slice,death_slice,how='inner',on='County')

In [37]:
income_death_data

,City,County,State_Name,Median_Income,Age-Adjusted Death Rate,Average Deaths per Year
0,Chickasaw,"Mobile County, Alabama",Alabama,30506,63.3,289
1,Satsuma,"Mobile County, Alabama",Alabama,52814,63.3,289
2,Dauphin Island,"Mobile County, Alabama",Alabama,67225,63.3,289
3,Mobile,"Mobile County, Alabama",Alabama,38231,63.3,289
4,Satsuma,"Mobile County, Alabama",Alabama,52275,63.3,289
...,...,...,...,...,...,...
26968,Cheyenne,"Albany County, Wyoming",Wyoming,69614,29.1,8
26969,Cheyenne,"Albany County, Wyoming",Wyoming,68371,29.1,8
26970,Diamondville,"Albany County, Wyoming",Wyoming,70752,29.1,8
26971,Casper,"Albany County, Wyoming",Wyoming,79809,29.1,8
26972,Powell,"Albany County, Wyoming",Wyoming,64557,29.1,8

In [38]:
income_incident_data.groupby('County').mean().reset_index()

                                 County  Median_Income
0      Abbeville County, South Carolina   43326.849462
1              Acadia Parish, Louisiana   42345.339623
2             Accomack County, Virginia   65267.573826
3                     Ada County, Idaho   45272.370370
4                    Adair County, Iowa   53179.632258
...                                 ...            ...
1289            Yuba County, California   46888.000000
1290  Yukon-Koyukuk Census Area, Alaska   30981.250000
1291               Yuma County, Arizona   31658.666667
1292              Yuma County, Colorado   37453.000000
1293               Zapata County, Texas   25479.000000

[1294 rows x 2 columns]

In [39]:
in_adj_income = income_incident_data.groupby('County').mean().reset_index() # Combine incomes of incidents by county

In [40]:
income_death_data.groupby('County').mean().round(0).reset_index()

                                County  Median_Income
0     Abbeville County, South Carolina        43327.0
1             Acadia Parish, Louisiana        42345.0
2            Accomack County, Virginia        65268.0
3                    Ada County, Idaho        45272.0
4                   Adair County, Iowa        53180.0
...                                ...            ...
1384         York County, Pennsylvania        54665.0
1385       York County, South Carolina        39903.0
1386               Young County, Texas        36772.0
1387           Yuba County, California        46888.0
1388             Yuma County, Colorado        37453.0

[1389 rows x 2 columns]

In [41]:
dt_adj_income = income_death_data.groupby('County').mean().reset_index() # Combine incomes of deaths

In [42]:
income_incident_data = pd.merge(in_adj_income,incident_slice,how='inner',on='County')

In [43]:
income_death_data = pd.merge(dt_adj_income,death_slice,how='inner',on='County')

In [44]:
income_incident_data

,County,Median_Income,Age-Adjusted Incidence Rate,Average Annual Count
0,"Abbeville County, South Carolina",43326.849462,68.1,24
1,"Acadia Parish, Louisiana",42345.339623,79.6,53
2,"Accomack County, Virginia",65267.573826,91.1,46
3,"Ada County, Idaho",45272.370370,52.2,191
4,"Adair County, Iowa",53179.632258,65.2,8
...,...,...,...,...
1289,"Yuba County, California",46888.000000,68.1,44
1290,"Yukon-Koyukuk Census Area, Alaska",30981.250000,58.3,3
1291,"Yuma County, Arizona",31658.666667,48,115
1292,"Yuma County, Colorado",37453.000000,62.5,8
1293,"Zapata County, Texas",25479.000000,38.2,4

In [45]:
income_death_data

,County,Median_Income,Age-Adjusted Death Rate,Average Deaths per Year
0,"Abbeville County, South Carolina",43326.849462,57.6,20
1,"Acadia Parish, Louisiana",42345.339623,68.6,46
2,"Accomack County, Virginia",65267.573826,76.7,38
3,"Ada County, Idaho",45272.370370,37.6,136
4,"Adair County, Iowa",53179.632258,42.3,5
...,...,...,...,...
1384,"York County, Pennsylvania",54664.666667,46,240
1385,"York County, South Carolina",39903.000000,54,124
1386,"Young County, Texas",36772.000000,60.2,16
1387,"Yuba County, California",46888.000000,55.3,35
1388,"Yuma County, Colorado",37453.000000,40.3,5

In [46]:
incident_death_data = pd.merge(income_incident_data,income_death_data,how='inner',on='County')

In [47]:
incident_death_data = incident_death_data.drop('Median_Income_y',axis=1)

In [48]:
incident_death_data.to_csv('C:\\Users\\Patricia\\Documents\\WGU\\CAPSTONE\\incident_death_data.csv',index=False)

In [49]:
income_death_data.to_csv('C:\\Users\\Patricia\\Documents\\WGU\\CAPSTONE\\income_death_data.csv',index=False)

In [50]:
income_incident_data.to_csv('C:\\Users\\Patricia\\Documents\\WGU\\CAPSTONE\\income_incident_data.csv',index=False)